export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_LOGIN_ERROR = "SET_LOGIN_ERROR";

export const SET_CHATS = "SET_CHATS";
export const CREATE_NEW_CHAT = "CREATE_NEW_CHAT";
export const SET_NEW_CHAT_ERROR = "SET_NEW_CHAT_ERROR";

export const SET_CONVERSATION = "SET_CONVERSATION";
export const SET_CONVERSATION_ERROR = "SET_CONVERSATION_ERROR";
export const ADD_CONVERSATION_MESSAGE = "ADD_CONVERSATION_MESSAGE";